In [1]:
import numpy as np

##  1D Arrays

In [2]:
np.zeros(5)       

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(5,10)         #np.full(dimension , value to be filled)

array([10, 10, 10, 10, 10])

In [5]:
a = np.array([1, 3, 6, 9])
a

array([1, 3, 6, 9])

In [6]:
np.arange(3,9)         # similar to range function

array([3, 4, 5, 6, 7, 8])

In [7]:
np.linspace(1,12, 6)

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

# Multi-Dimension Arrays