In [1]:
import numpy as np

##  1D Arrays

In [2]:
np.zeros(5)       

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(5,10)         #np.full(dimension , value to be filled)

array([10, 10, 10, 10, 10])

In [5]:
a = np.array([1, 3, 6, 9])
a

array([1, 3, 6, 9])

In [6]:
np.arange(3,9)         # similar to range function

array([3, 4, 5, 6, 7, 8])

In [7]:
np.linspace(1,12, 6)

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

# Multi-Dimension Arrays

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
a = np.array([[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
a[0]

array([1, 2, 3])

In [16]:
a[:,1]

array([2, 5, 7])

In [20]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [21]:
np.random.randint(low=0,high=99,size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

# Element-wise operations

In [29]:
n = np.arange(5)
n

array([0, 1, 2, 3, 4])

In [31]:
n + 50


array([50, 51, 52, 53, 54])

In [32]:
n[n>2]

array([3, 4])

# summarizing

In [33]:
n.mean()

2.0

In [34]:
n.max()

4