# Linear Algebra

### Dot product

In [1]:
import numpy as np

In [2]:
u = np.array([1, 4, 6, 3])
v = np.array([2, 4, 5, 9])

In [3]:
v

array([2, 4, 5, 9])

In [4]:
v.shape   # returns a tuple

(4,)

In [25]:
def dot_product(u, v):
    assert u.shape[0] == v.shape[0]
    
    result = 0.0
    
    n = v.shape[0]
    
    for i in range(n):
        result += u[i]*v[i]
        
    return result

In [6]:
dot_product(u,v)

75.0

In [7]:
v.dot(u)

75

### Matrix vector multiplication

In [12]:
M = np.array([[1, 3, 4],
              [2, 4, 5],
              [8, 4, 1]]) # matrix
M

array([[1, 3, 4],
       [2, 4, 5],
       [8, 4, 1]])

In [10]:
M.shape

(3, 3)

In [11]:
n = np.array([2, 5, 3]) # vector

In [34]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    
    num_of_rows = U.shape[0]
    
    result = np.zeros(num_of_rows)
    
    for i in range(num_of_rows):
        result[i] = dot_product(U[i],v)
        
    return result
        

In [35]:
matrix_vector_multiplication(M,n)

array([29., 39., 39.])

In [36]:
M.dot(n)

array([29, 39, 39])